# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'shiny-ocr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shiny-ocr
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'SPIndicator'
end
